### ISSUE TITLE
deprecate git community book

### ISSUE THREAD

**Issue by schacon** [git/gitscm-old#48]
replace all urls with redirects to pro git or tutorial equivalents

**Comment by matthewmccullough** [comment]
I always hate/love killing stuff. Is all the intellectual value preserved in the other materials?

**Comment by schacon** [comment]
Almost everything is either in the Git Manual or Pro Git.  There are a few things like detailed packfile format docs and git protocol specs that are not really elsewhere, so I may just add to Pro Git to incorporate them.

**Comment by bwheatley** [comment]
Yes please do that scott.  The community book had some references that were more in depth than the pro git book.

**Comment by shafiul** [comment]
I really liked the interface and literature of the Community Book. It was easy to understand.
