### ISSUE TITLE
git-config manpage 404ing

### ISSUE THREAD

**Issue by marr** [git/gitscm-old#54]
http://book.git-scm.com/5_customizing_git.html links to http://www.kernel.org/pub/software/scm/git/docs/git-config.html which is 404ing.

**Comment by matthewmccullough** [comment]
There's some active effort going on to clean up many things about the site and I'll put this on my checklist to verify after the big updates. Thanks for bringing it up!  Darn that kernel.org attack.  Caused so many links to break.
