### ISSUE TITLE
Wide preformatted text cannot be viewed

### ISSUE THREAD

**Issue by frioux** [git/gitscm-old#58]
See http://git-scm.herokuapp.com/docs/git-merge/1.7.10, the HOW CONFLICTS ARE PRESENTED section.  The overly wide text is unviewable.  I think the best thing to do would probably be to add a scrollbar if the content is too wide.  Of course if the content is wide _and_ tall then a single scrollbar at the bottom is really frustrating too...

**Comment by onia** [comment]
:heavy_exclamation_mark:
